### ISSUE TITLE
Switching quality doing nothing

### ISSUE THREAD

**Issue by HeeroML** [Jman012/Wasserflug-tvOS#2] opened 2022-05-04 18:39 UTC
I tried switching to 4K and don't know if it really is 4k, it didn't look like it. Switching also didn't change playback. AppleTV 4k 2021 latest non beta tvOS. 
Latest App Store version of wasserflug

Edit: Version 1.0.6

**Comment by Jman012** [comment] 2022-05-04 18:44
Hi Heero. So for example, when you switch from 720p to 1080p, there's a small delay while it fetches the new video stream, but when you switch from 1080p to 4K/2160p, it doesn't have that small delay? That would certainly indicate that it's not actually switching to the 4K stream. 

I might need to upgrade my account and test out 4K myself.

**Comment by HeeroML** [comment] 2022-05-04 18:45
Correct. I can provide additional info if you want.

**Comment by Jman012** [comment] 2022-05-04 18:49
Any additional information you have would be appreciated.

There's one part in the code where it might skip an update to the current video, but that's only if the URL found to have not changed. When switching from 1080p to 4K, the URL should definitely be different.

What happens if you keep it at 4K (the app will remember your preference), exit the video, and come back to the video? Can tou discern if it's playing in 4K feedback at that point? Or perhaps, does another video work with a 1080p->4K switch but not a particular one (and if so, which video are you seeing this behavior on)?

**Comment by HeeroML** [comment] 2022-05-04 18:55
So I looked into your code a bit. But first your questions: 
It's not 4K, I notice that cause of details and load speed. Every video is affected. But I could see, that your check für resolution could be not working, I also don't get why you have this at all 😀  It should just default to screen resolution on first Start, but otherwise I don't get why I didn't want to use the higher Bitrate 4K Version eben on 1080p.

**Comment by HeeroML** [comment] 2022-05-04 18:59
Oh randomly in the FP exclusive Linus surprised us, 4K does work. 
> So I looked into your code a bit. But first your questions: 
> It's not 4K, I notice that cause of details and load speed. Every video is affected. But I could see, that your check für resolution could be not working, I also don't get why you have this at all 😀  It should just default to screen resolution on first Start, but otherwise I don't get why I didn't want to use the higher Bitrate 4K Version even on 1080p.

**Comment by Jman012** [comment] 2022-05-04 19:03
Do you mean this bit of code?

```swift
// Filter out resolutions larger than the device's screen resolution
let result = CGFloat(qualityLevel.width) <= screen.bounds.width
if !result {
	self.logger.warning("Ignoring quality level \(String(describing: qualityLevel)) due to larger-than-screen width of \(screen.bounds.width)")
}
return result
```

This is so that if someone has a 4K apple TV hooked up to a 1080p display, then they don't see the 4K option. It would take up more bandwidth than is needed and put more strain on the Apple TV to downsize it.

As for defaulting to screen size, I think that Floatplane/LTT likes to choose some interesting/non-standard video resolutions. After the user selects 1080p, then it should stick to that selection going forward, for example.

I'm not sure why this wouldn't be working either. I'll upgrade to the 4K tier and take a look to see what's going on under the hood. Thanks! I wish it'd be easier to get device logs from users. According to https://developer.apple.com/documentation/xcode/acquiring-crash-reports-and-diagnostic-logs#Access-Device-Console-Logs you'd have to connect your Apple TV to a Mac and everything, which is a lot of work.

**Comment by HeeroML** [comment] 2022-05-04 19:05
Do you log everything already? Then I could try to export the logs tomorrow

**Comment by Jman012** [comment] 2022-05-04 19:06
I do try to log as much as possible. Though I think that by default it only logs `notice` and up, not `debug` or `info`.

**Comment by HeeroML** [comment] 2022-05-04 19:07
I have TestFlight installed right now, if this helps

**Comment by Jman012** [comment] 2022-05-04 22:55
I think that article I linked only needs the Console app to read the logs. Though, I'm not sure how "connect the device to your Mac" works without Xcode. It might automatically pick it up over the network, or you might need to connect it over a USB cable.

I emailed FP support to upgrade to the 4K tier so I should be able to reproduce it soon enough. Don't download Xcode if you don't need it :).

**Comment by Jman012** [comment] 2022-06-19 19:04
This has been addressed in version 1.2.0. This version will release to Test Flight public beta in 1 or 2 days. Please let me know if this fixes the issue for you once it's available and you're able to test it, @HeeroML!

The problem was that I did have logic to filter out videos that exceeded the screen width of the device (so that 4K videos wouldn't appear on 1080p televisions unnecessarily), but I forgot to actually remove those resolutions from the picker. So, choosing 4K would just default to 1080p, and thus the video wouldn't reload at a different resolution. I fixed this to only show the right resolutions in the picker, but also to allow for LTT's larger-than-normal videos by giving a 15% allowance. I confirmed that 1080p videos (2160x1080) would appear on 1080p screens (1920x1080). Let me know if 4K stops appearing for you.

**Comment by Jman012** [comment] 2022-07-03 17:09
Over in #7 others have reported 4K is indeed missing. I will provide a fix for both of these issues.

**Comment by Jman012** [comment] 2022-07-03 22:58
This should be fixed in `1.2.1 (1)` once it becomes public on the Test Flight (should be within the next 48 hours).

**Comment by Jman012** [comment] 2022-07-15 15:26
Version 1.2.1 has gone out to the App Store for review and publication.

**Comment by Jman012** [comment] 2022-09-07 20:56
This has been fixed. Closing.

**Closed by Jman012** 2022-09-07 20:56 UTC
Labels: bug

**Comment by HeeroML** [comment] 2022-09-08 23:14
Can confirm now. Have 4K now
